version: '3'
services:
  t1cg-io:
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    image: t1cg-io-img
    container_name: t1cg-io
    volumes:
      - ../src:/usr/src/t1cg-io/src
    ports:
      - "4001:4001"
