version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    volumes:
      # - ./setup.js:/docker-entrypoint-initdb.d/setup.js
      - mongo_training:/data/db
    build:
      context: ../api
      dockerfile: ../Docker/Dockerfile.api.dev
    ports:
      - '80:8081'
  mongo:
    container_name: mongo
    image: mongo
    # start mongo on this port
    command: mongod --port 27017
    # map the port started with mongo above to new port on your (host) computer
    ports:
      - 27031:27017
   
  # react_training:
  #   container_name: react_training
  #   build:
  #     context: ../ui
  #     dockerfile: ../Docker/Dockerfile.ui.dev
  #   ports: 
  #     - '3000:3000'
  #   stdin_open: true
  #   tty: true
volumes:
  mongo_training: